version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "LannisterAPI" -c %CONFIGURATION% --version-suffix %LABEL%
after_build:
- dotnet publish "LannisterAPI" -c %CONFIGURATION% --version-suffix %LABEL% -o .\..\artifacts
- ps: Compress-Archive -Path "artifacts\*" -DestinationPath "artifacts.zip"
artifacts:
- path: artifacts.zip
deploy:
  provider: FTP
  protocol: ftp
  host:
    secure: wxerQP2q5gIQZ5HY/eP0S+iROzbaRRHWfIKtr1rLZP8=
  username:
    secure: KKJYq0FwgGfZTfOlwFNFwR52AyHcBjcaXny0y2lyCOY=
  password:
    secure: x/elDXXySkDI0Zp5Ya6xXQ==
  application: artifacts.zip
